version: 2
jobs:
  test:
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "glide.lock" }}
      - run:
          name: make bootstrap
          command: make bootstrap
      - save_cache:
          key: dependency-cache-{{ checksum "glide.lock" }}
          paths:
            - vendor
      - run:
          name: make test
          command: make test
      - run:
          name: make coverage
          command: make coverage
