version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Azure/acs-engine
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: make bootstrap
      - run:
          name: Build binaries
          command: make build
      - run:
          name: Run unit tests
          command: make test
      - run:
          name: make coverage
          command: make coverage
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
