version: 2
jobs:
  bootstrap:
    working_directory: /go/src/github.com/Azure/acs-engine
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "glide.lock" }}
      - run:
          name: make bootstrap
          command: make bootstrap
      - save_cache:
          key: dependency-cache-{{ checksum "glide.lock" }}
          paths:
            - vendor
  build:
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "glide.lock" }}
      - run:
          name: make test
          command: make test
      - run:
          name: make coverage
          command: make coverage
workflows:
  version: 2
  build_and_test:
    jobs:
      - bootstrap
      - build:
          requires:
            - bootstrap
